### ISSUE TITLE
"paths" key in package.json is "reserved for future expansion"

### ISSUE THREAD

**Issue by benface** [nystudio107/craft#10]
I was curious about your use of custom keys in `package.json`, so I looked it up, and while it is valid, the `paths` key name is not because it is "reserved for future expansion" ([Source](https://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid)).

**Comment by khalwat** [comment]
Welp, looks like that's been reserved for at least 4 years. If they ever end up using it, I suppose I could change it.
