### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages"

### ISSUE THREAD

**Issue by slebbo** [nystudio107/craft#11]
When I try to run the setup command composer tells me this;

```composer create-project nystudio107/craft craft3project -s RC
Installing nystudio107/craft (1.0.14)
  - Installing nystudio107/craft (1.0.14): Loading from cache
Created project in craft3project
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - craftcms/cms 3.0.0-RC10 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - craftcms/cms 3.0.0-RC10.1 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - craftcms/cms 3.0.0-RC7 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - craftcms/cms 3.0.0-RC7.1 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - craftcms/cms 3.0.0-RC8 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - craftcms/cms 3.0.0-RC9 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13, 2.0.13.1].
    - yiisoft/yii2 2.0.13 conflicts with roave/security-advisories[dev-master].
    - yiisoft/yii2 2.0.13.1 conflicts with roave/security-advisories[dev-master].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Installation request for craftcms/cms ^3.0.0-RC7 -> satisfiable by craftcms/cms[3.0.0-RC10, 3.0.0-RC10.1, 3.0.0-RC7, 3.0.0-RC7.1, 3.0.0-RC8, 3.0.0-RC9].
```

Is there a setting I've missed? 
I'm using Composer version 1.6.3 on macOS 10.13.3 (17D47) with PHP 7.1.7 (cli)

(I've also tried to run the command in my vagrant homestead box but with same result)

**Comment by khalwat** [comment]
yeah I've updated it to fix this... looks like the `roave/security-advisories` is the issue in 1.0.15:

https://github.com/nystudio107/craft/releases/tag/1.0.15

If you want to fix it for an existing setup, just sync the `composer.json` with what is here:

https://github.com/nystudio107/craft/blob/master/composer.json

**Comment by slebbo** [comment]
Niceness! This setup is perfect - thanks for responding so quickly ✊🤩

**Comment by fmkguy** [comment]
I'm getting a similar problem when trying to install the latest version (`1.0.15`):

```
Installing nystudio107/craft (1.0.15)
  - Installing nystudio107/craft (1.0.15): Loading from cache
Created project in craftny
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/process v4.2.3 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - symfony/process v4.2.2 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - symfony/process v4.2.1 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - symfony/process v4.2.0-RC1 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - symfony/process v4.2.0 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - ostark/craft-async-queue dev-master requires symfony/process ^4.2.0 -> satisfiable by symfony/process[v4.2.0, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3].
    - Installation request for ostark/craft-async-queue dev-master -> satisfiable by ostark/craft-async-queue[dev-master].
```

**Comment by tommers-walker** [comment]
> I'm getting a similar problem when trying to install the latest version (`1.0.15`):
> 
> ```
> Installing nystudio107/craft (1.0.15)
>   - Installing nystudio107/craft (1.0.15): Loading from cache
> Created project in craftny
> > @php -r "file_exists('.env') || copy('.env.example', '.env');"
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - symfony/process v4.2.3 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
>     - symfony/process v4.2.2 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
>     - symfony/process v4.2.1 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
>     - symfony/process v4.2.0-RC1 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
>     - symfony/process v4.2.0 requires php ^7.1.3 -> your PHP version (7.2.9) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
>     - ostark/craft-async-queue dev-master requires symfony/process ^4.2.0 -> satisfiable by symfony/process[v4.2.0, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3].
>     - Installation request for ostark/craft-async-queue dev-master -> satisfiable by ostark/craft-async-queue[dev-master].
> ```

Same for me
