### ISSUE TITLE
Local assets generated without staticAssetsVersion timestamp

### ISSUE THREAD

**Issue by nickcotton** [nystudio107/craft#15]
I've set up a new site and running `gulp` generates assets without error, but without the staticAssetsVersion string in the file name. I happens for site.combined.min.css, vue.min.js and axios.min.js.

Craft seems to be requesting the timestamped assets so I don't think the problem is there. I've tried running gulp from within my homestead box and I get the same result. Let me know what other info I can provide to help.

Thanks!

**Comment by nickcotton** [comment]
Ahh, missed this step in the guide: https://nystudio107.com/blog/simple-static-asset-versioning#server-setup

**Comment by NickToye** [comment]
Problem I am having with this is the .htaccess in that guide, and the one that comes with the setup are conflicting with each other.  

This is what I have ended up with:

```
<IfModule mod_rewrite.c>
	RewriteEngine On

	# Send would-be 404 requests to Craft
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
	RewriteRule ^(.+)\.(\d+)\.(bmp|css|cur|gif|ico|jpe?g|js|png|svgz?|webp|webmanifest)$ $1.$3 [L]
	RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

So my admin loads, but my front end doesn't.  I get this error:

**Template not found: index.php**

If I go with what is in the guide above then the admin fails to load but the front end works fine.

What am I doing wrong?

**Comment by mtmchad** [comment]
I have the same issue, either admin or front-end loads depending on the .htaccess file I use.
