### ISSUE TITLE
cannot install using command in README on OS X

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft#2]
On OS X 10.12.6 the composer create-project command fails.

```
➔ composer --version
Composer version 1.5.2 2017-09-11 16:59:25

➔ composer create-project nystudio107/craft . -s RC

  [InvalidArgumentException]
  Could not find package nystudio107/craft with stability RC.

```

**Comment by khalwat** [comment]
Right, for you to use it right now, you'll need to do:

```
composer create-project nystudio107/craft PATH -s dev
```

btw, don't use `.` for the PATH, you'll want at least a relative folder name in there, like:

```
composer create-project nystudio107/craft testsite -s dev
```

I didn't expect anyone to be using this quite yet (thus no release tags), it's still a work in progress... but keep any issues coming! :)
