### ISSUE TITLE
/cpresources doesn’t exist or isn’t writable by PHP.

### ISSUE THREAD

**Issue by modulareverything** [nystudio107/craft#21]
After installing, I get the following error;

> /cpresources doesn’t exist or isn’t writable by PHP.

Any ideas? This was after following the instructions in the readme to the letter. I've tried solving this myself by changing the write access but it didn't seem to make a difference.

Any suggestions?

**Comment by tyssen** [comment]
I'm getting the same thing. I've just run the installation on my Mac and have set permissions to read & write for everyone, but the error persists.

**Comment by johnfmorton** [comment]
One guess is that your .htaccess file is missing in your web directory, assuming you’re using Apache.

**Comment by tyssen** [comment]
No, it's there and permissions are OK.

**Comment by seamusmh** [comment]
I've gotten that error before because the URL & webfoot paths didn't get set in the .env file during setup.

**Comment by tyssen** [comment]
Yeah mine were both empty. I've updated my `.env` file and now the error is pointing to the correct location but still saying it's not writeable or doesn't exist.

**Comment by seamusmh** [comment]
Try these next: turn on dev mode, run `yarn build`, run ./nys-setup, run `composer update`. Usually one of those resolves the issue or points me in the right direction. You're sure the webroot is accurate?

**Comment by tyssen** [comment]
The problem was my WEB_ROOT_PATH has spaces in it. I thought putting it between `""` would be fine, but I had to put it between `"' '"`, i.e. double and single quotes.

**Comment by tyssen** [comment]
Actually, that hasn't quite solved the problem. When I access anything in the control panel now, I get a folder path like this created in my web folder:

'
-Users
--username
---path
----to
-----folder
------web
-------cpresources
etc.

and it's that cpresources folder, not the one directly below web which is filling up with assets.

**Comment by tyssen** [comment]
Seems like the answer is `WEB_ROOT_PATH="."`.

**Comment by mikestecker** [comment]
I ended up having to set it to `WEB_ROOT_PATH="web"` for it to function properly

**Comment by khalwat** [comment]
So this is all fixed up in the current incarnation, which is a Docker-ized setup
