### ISSUE TITLE
question: how to load /src/img/ assets into webpack-dev-server?

### ISSUE THREAD

**Issue by Tim-Wils** [nystudio107/craft#27]
Hi!
I nearly got this working. Even with a webpack-dev-server with https and certificate stuff, but then I walked into a problem with hot module reloading and "background-image: url(/img/header1.jpg)" in homepage.pcss.

I cannot get these ones to work:
url(/dist/img/header1.jpg)
url(/img/header1.jpg)
url(../img/header1.jpg)
url(../../img/header1.jpg)
url(/src/img/header1.jpg)

I peeked here to see if I could get an example of a local image in pcss, but they a pointed towards an cloudfront url:
https://github.com/nystudio107/devmode/blob/master/src/css/components/global.pcss

Do you have a solution for this to get it right?

Thanks,
Tim

**Comment by khalwat** [comment]
Probably this is a question for the webpack repo -> https://github.com/nystudio107/annotated-webpack-4-config
