### ISSUE TITLE
php-dev-base - Github connection

### ISSUE THREAD

**Issue by hugo-costa** [nystudio107/craft#29]
After a while the following error appears:
`Failed to download tubalmartin/cssmin from dist: Could not authenticate against github.com`

When using `docker-compose up` composer stops working due to maximum requests to hit Github. Github support 60 requests, a token can be generated on Github and applied in composer using the below:
`composer config -g github-oauth.github.com <token id>`

Can we specify this token somewhere so it passed to the container above?

**Comment by khalwat** [comment]
That's interesting, I wonder why I haven't run into this limitation?

**Comment by hugo-costa** [comment]
Maybe im doing thing wrong? (never rule that out)

I think a simple fix this may be to add this to docker environment variables.

`COMPOSER_AUTH={"github-oauth":{"github.com":"your-token-here"}}`

Haven't tested yet, but will give it a go some day this week.

**Comment by hugo-costa** [comment]
Tested with the above and it worked for me.
