### ISSUE TITLE
Seeding the database

### ISSUE THREAD

**Issue by Bcdo** [nystudio107/craft#32]
When trying to import the seed_db.sql database dump the first time from the scripts/ dir, I get command not found.

**Comment by Bcdo** [comment]
Had to change the permission for the script, for some reason it did not show permission denied.

**Comment by cavellblood** [comment]
This still seems to be the case. The file permissions in `scripts` still looks like this:

```
drwxr-xr-x   8 cavellblood  staff   256 Nov 12 17:15 .
drwxr-xr-x  14 cavellblood  staff   448 Nov 12 17:15 ..
-rw-r--r--   1 cavellblood  staff  1622 Nov 12 20:34 .env.sh
drwxr-xr-x   7 cavellblood  staff   224 Nov 11 21:42 common
-rwxr-xr-x   1 cavellblood  staff   971 Nov 11 21:42 docker_prod_build.sh
-rwxr-xr-x   1 cavellblood  staff  4125 Nov 11 21:42 docker_pull_db.sh
-rw-r--r--   1 cavellblood  staff  2337 Nov 11 21:42 docker_restore_db.sh
-rw-r--r--   1 cavellblood  staff  1563 Nov 11 21:42 example.env.sh
```

The `docker_restore_db.sh` is not executable by default. Had to change the permissions for it to work.
