### ISSUE TITLE
Add support for ImageOptimize transformers

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft#36]
Can you update the Dockerfile to auto install all of the image processors supported by your ImageOptimize plugin?

Here's the list from the default config for reference:

- [ ] `jpegoptim`
- [ ] `mozjpeg`
- [ ] `jpegtran`
- [ ] `optipng`
- [ ] `pngcrus`
- [ ] `pngquant`
- [ ] `svgo`
- [ ] `gifsicle`
- [ ] `cwebp`

**Comment by khalwat** [comment]
Good idea, I like it

**Comment by khalwat** [comment]
The ones that are pre-built as packages I've added.
