### ISSUE TITLE
mysqldump not found

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft#37]
I was trying to pull a backup of the database from within the GUI and it kept failing. Looking at the logs, I get:

```
mysqldump: not found in /var/www/project/cms/vendor/craftcms/cms/src/controllers/UtilitiesController.php:377
```

**Comment by khalwat** [comment]
Possible it's not installed in the docker container

**Comment by khalwat** [comment]
You can add this yourself if you need it... it's not something I use locally.
