### ISSUE TITLE
Speed up webpack compile time

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft#38]
Hi Andrew,

First of all. Loving the package. It gave us a great kick-off for Craft CMS in Docker.
All is running great except the speed of the webpack compile proces. It takes at least 15 seconds on every change.

I can't imagin you can work like that so i'm probably missing something. I already gave docker more cpu (6) en more memory (8 GB) . But the result is the same. Some Googling led me too setting the volumes to cached/delegated but you've already set that in the package.

Do you have any other ideas?

**Comment by khalwat** [comment]
I don't have an answer for you without significantly more information, but 15 seconds is a very long time. It should only be a few seconds in general.

I will say that Tailwind is quite slow at rebuilding, if it's CSS that you're changing. If it's JavaScript, it should HMR nicely.
