### ISSUE TITLE
Local dev without docker?

### ISSUE THREAD

**Issue by pjdevries** [nystudio107/craft#39]
### Question
Is it feasable to set this up in a local development environment without docker?

### Additional context
My current local development system is Windows 10 based (yeah I know). I have been playing with docker once upon a time, but performance is horrible. So I do all my development in a WAMP environment, I would appreciate pointers how to set this up in that environment.

**Comment by Bcdo** [comment]
It is very feasable, but it does take a bit of work to reverse engineer this repo to work with something besides docker. I have had the same problem, and I made a version to be used with Craft Nitro. 

But, I would recommend using docker and see if you can make it work with better performance, as the whole point of the scaffolding project is to set it up quick and easy, with minimal chance of things going wrong. Setting up the project oustide of docker, takes much longer and in a way defeats much of the purpose.

**Comment by pjdevries** [comment]
Thanx for the reply. Maybe it's about time for a descent Linux development system :)

**Comment by iuscare** [comment]
@pjdevries maybe check out the commits. This package has gone a long way and @khalwat has improved it continuously. Previous versions were working without docker (webpack only) and even with gulp. Most of the goodies are also in the webpack standalone package, beside typescript and vue3 support and some other minor improvements which can be re-implemented easily.

E.g.: https://github.com/nystudio107/craft/tree/bbdd444471452f4611c3d177a3b361911088ccd2

**Comment by khalwat** [comment]
So this repo is the boilerplate that we use at nystudio107.

You're welcome to use it yourself, or just pick the pieces you want to use from it, or learn from it.

But in general, it's always going to be very opinionated, and reflect that we're using at the time.

We've moved to a Docker-based setup for local dev, so....
