### ISSUE TITLE
missing plugin craft3-pathtools

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft#4]
`craft3-pathtools` is a requirement for the base` _layout.twig` file, but is not included in the scaffolding package.

**Comment by khalwat** [comment]
I removed the dependency on PathTools from `_layout.twig` -- but I haven't gone through that file completely to refactor it yet... and there are some additional scaffolding files I'll be adding.

I didn't expect anyone to be using this quite yet (thus no release tags), it's still a work in progress... but keep any issues coming! :)
