### ISSUE TITLE
When Installing Composer Packages from Git `git` is needed.

### ISSUE THREAD

**Issue by simeon-smith** [nystudio107/craft#40]
### Is your feature request related to a problem? Please describe.
When the php-dev-craft docker container was setup it was failing because I had a composer package that was being sourced from GitHub.

### Describe the solution you would like
Adding `git` to the `apt-get install -y` portion of the php-dev-craft Dockerfile resolves this.

### Describe alternatives you have considered
I don't think there's an alternative since composer requires git to install from a git repo.

**Comment by khalwat** [comment]
Yep, that makes sense -- and if you're using git-based repos, you should add that to your `php-dev-craft`
