### ISSUE TITLE
Keep running into PHP error while building docker

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft#48]
Keep getting these errors while trying to install this container. 

    docker-compose up
    Removing craft-boilerplate_php_1
    craft-boilerplate_webpack_1 is up-to-date
    craft-boilerplate_nginx_1 is up-to-date
    craft-boilerplate_redis_1 is up-to-date
    craft-boilerplate_mariadb_1 is up-to-date
    Starting 64f8ef9b3d9b_craft-boilerplate_php_1 ... error
    
    ERROR: for 64f8ef9b3d9b_craft-boilerplate_php_1  Cannot start service php: OCI runtime create failed:                     
    container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59:       
    mounting "/var/lib/docker/volumes/craft-boilerplate_cpresources/_data" to rootfs a "/var/lib/docker/overlay2/05d1b066bf1d20fb2ca0c94883798829e304806a7283343014adfcb8d3c579f7/merged/var/www/pr    oject/cms/web/cpresources" caused: mkdir /var/lib/docker/overlay2/05d1b066bf1d20fb2ca0c94883798829e304806a7283343014adfcb8d3c579f7/merged/var/www/project/cms/web/cpresources: no such file or directory: unknown

    ERROR: for php  Cannot start service php: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/lib/docker/volumes/craft-boilerplate_cpresources/_data" to rootfs at "/var/lib/docker/overlay2/05d1b066bf1d20fb2ca0c94883798829e304806a7283343014adfcb8d3c579f7/merged/var/www/project/cms/web/cpresources" caused: mkdir /var/lib/docker/overlay2/05d1b066bf1d20fb2ca0c94883798829e304806a7283343014adfcb8d3c579f7/merged/var/www/project/cms/web/cpresources: no such file or directory: unknown
    ERROR: Encountered errors while bringing up the project.

**Comment by khalwat** [comment]
This was a bug in Docker desktop 3.0.2 -- update to 3.0.3 and it'll be fixed
