### ISSUE TITLE
gulpfile - wrong src path for imagemin

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft#5]
https://github.com/nystudio107/craft/blob/168498fa699e2e22853d53621fbe538021e8c0e0/gulpfile.js#L328

**Comment by khalwat** [comment]
This is actually the correct path. It minimizes them in place. Unless I'm missing something?

**Comment by robinleblon** [comment]
If it is intended to minimize them in place, then it is indeed correct.

To me however, it seems odd to do it this way.
In your src folder you expect gulp to leave everything intact, while processed things should go to dist or build. If imagemin messes up a picture, there is a risk that you lose the original file.

It also does not really align with the rest of the gulp tasks, which all output to the dist folder.
Additionally, it requires another additional copy step you either need to do manually, or add yourself in the gulpfile, which kind of defeats the purpose...
Suppose that could be solved with a general copy task, where src and dests can be added in package.json

**Comment by khalwat** [comment]
Yep, you're right, and the way you're discussing it is how I historically did it -- but what I found was that it was really tedious to run, and watch it re-minimize the images each time.

Whereas if you have it overwrite the destination image, it will recognize it is minimized, and do very little.

So, it's up to you. If you'd prefer it to minimize each run through (maybe only on deploy), set it back to `/src/img/`

**Comment by khalwat** [comment]
...which I just did:

```
// imagemin task
gulp.task("imagemin", () => {
    return gulp.src(pkg.paths.src.img + "**/*.{png,jpg,jpeg,gif,svg}")
        .pipe($.imagemin({
            progressive: true,
            interlaced: true,
            optimizationLevel: 7,
            svgoPlugins: [{removeViewBox: false}],
            verbose: true,
            use: []
        }))
        .pipe(gulp.dest(pkg.paths.dist.img));
});
```
