### ISSUE TITLE
CP Homepage editing page is empty

### ISSUE THREAD

**Issue by Maybach91** [nystudio107/craft#52]
### Describe the bug
After a fresh install and import of the sql dump i cannot see any elements within the Homepage

### To reproduce
Steps to reproduce the behaviour:
1. Install via composer
2. Run `docker exec` on the mariadb image and import the seed_db.sql (i unzipped it before via macOS Finder)
3. Go to http://localhost:8000/admin/entries/homepage/2-homepage and see only the sidebar with information

### Expected behaviour
Reflection of the Content visible on the Frontend
![image](https://user-images.githubusercontent.com/1867543/109386568-c9a39f00-78fb-11eb-8e94-88434127c9ab.png)

### Screenshots

![image](https://user-images.githubusercontent.com/1867543/109386527-792c4180-78fb-11eb-810f-bcdf877b4ec2.png)

### Versions
- Craft version: 3.6.7

Not sure if this is desired behaviour tho

**Comment by khalwat** [comment]
There are no fields added to the homepage single by default, so this is expected behavior.
