### ISSUE TITLE
webpack-dev-server crashes on v4.0.0-beta.1 - move overlay option into client option

### ISSUE THREAD

**Issue by iuscare** [nystudio107/craft#54]
### Describe the bug
When installing the latest version of the package no files are being injected into the templates when running locally. Could be a problem with nodemon/webpack, the output is as follows:

```
...
webpack_1     | [nodemon] 2.0.7
webpack_1     | [nodemon] to restart at any time, enter 'rs'
webpack_1     | [nodemon] watching path(s): webpack.dev.js webpack-configs/**/* webpack-settings/**/*
webpack_1     | [nodemon] watching extensions: js,mjs,json
webpack_1     | [nodemon] starting `webpack serve --config webpack.dev.js`
webpack_1     | [webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
webpack_1     |  - configuration has an unknown property 'overlay'. These properties are valid:
webpack_1     |    object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
webpack_1     | [nodemon] app crashed - waiting for file changes before starting...
...
```

The site itself is reachable, but no assets are being injected. I am also unable to reach the manifest.json with the browser. Is this a bug or am I missing something fundamental?

### To reproduce
Steps to reproduce the behaviour:
1. composer create-project nystudio107/craft craft3 --no-install
2. cd craft3
3. make dev

### Expected behaviour
The js bundles should be injected into the templates with HMR in place.

### Screenshots
<img width="1425" alt="Bildschirmfoto 2021-03-24 um 11 51 56" src="https://user-images.githubusercontent.com/33871309/112299047-b59f5300-8c97-11eb-9ad4-ed69f3079d68.png">

**Comment by khalwat** [comment]
The issue here isn't Nodemon, it's `webpack-dev-server` -- can you check your `package.lock` and see what version of that is installed?

**Comment by khalwat** [comment]
Okay yep it's as expected, they changed the config in the latest `beta.1` release of `webpack-dev-server`: 

https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.1

I'll fix it.

**Comment by iuscare** [comment]
Ah, sorry for being a little bit slow. Can confirm that I am running on 4.0.0-beta.1 and in that case moving the overlay prop into the client object solves it for me.
