### ISSUE TITLE
`make dev`’s if condition does not work

### ISSUE THREAD

**Issue by Maybach91** [nystudio107/craft#56]
### Describe the bug
After merging the newest version into my repo i tried to run `make dev` to start the docker container. But it just outputs the if condition and not starting the docker containers.

### To reproduce
Steps to reproduce the behaviour:
1. Merge current repo version into previous released craft-webpack branch
2. Update composer + npm packages
3. Run `make dev`
4. Get Terminal output:
```bash
if [ ! "$(docker ps -q -f name=${CONTAINER})" ]; then \
        docker-compose up; \
    fi
```	

### Expected behaviour
Start docker containers

### Screenshots
![image](https://user-images.githubusercontent.com/1867543/113124018-62884b80-9215-11eb-8435-6c9ebf83f861.png)
![image](https://user-images.githubusercontent.com/1867543/113124600-f8bc7180-9215-11eb-94c7-817e52c805cd.png)
![image](https://user-images.githubusercontent.com/1867543/113124617-fd812580-9215-11eb-8150-866821419002.png)

### Versions
- Craft version: `3.6.9`
- macOS: 11.2.3

**Comment by Maybach91** [comment]
Okay, got it work by removing one of the `$` in the Makefile at the `up` command.
https://github.com/nystudio107/craft/blob/57fcd05272aa14490a3716d1189166054c0dfe9b/Makefile#L24

From this:
`if [ ! "$$(docker ps -q -f name=$${CONTAINER})" ]; then \`  
  
to this:  
`if [ ! "$$(docker ps -q -f name=${CONTAINER})" ]; then \`

**Comment by khalwat** [comment]
Ah thanks, yep, I need to fix this!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft/commit/badfbb8029ec607db137e37768d76e7220bd73a4
