### ISSUE TITLE
craft.config.general should be craft.config

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft#6]
Multiple occurences craft.config.general.X should be replaced with craft.config.X

https://github.com/nystudio107/craft/blob/168498fa699e2e22853d53621fbe538021e8c0e0/templates/_layouts/_layout.twig#L2

**Comment by khalwat** [comment]
For Craft 3, they actually should be `craft.app.config.general.[setting]` https://github.com/craftcms/docs/blob/master/en/upgrade.md#template-functions

Fixed.

**Comment by robinleblon** [comment]
Hmm you are right.
In the latest beta however, it does yield on error. I suppose it will be fixed by the RC...

**Comment by khalwat** [comment]
You can point it at the RC by doing:

```
        "craftcms/cms": "dev-release/3.0.0-RC1 as 3.0.0-RC1",
```
