### ISSUE TITLE
Cannot install craft-vite branch

### ISSUE THREAD

**Issue by joepagan** [nystudio107/craft#60]
### Describe the bug

Appreciate you may be aware of this already and may be on your agenda, and has maybe been a couple months since your blog post on this but, cannot successfully install craft-vite branch using steps from https://github.com/nystudio107/craft/tree/craft-vite#using-nystudio107craft

Of course let me know if I'm being a fool and doing something wrong here..

```
composer create-project nystudio107/craft:dev-craft-vite vitecraft3 --no-install --remove-vcs
cd vitecraft3
make dev
```

results in:

```
Creating vitecraft3_mariadb_1 ... done
Creating vitecraft3_vite_1    ... done
Creating vitecraft3_redis_1   ... done
Creating vitecraft3_nginx_1   ...
Creating vitecraft3_php_1     ... error

Creating vitecraft3_nginx_1   ... done
ermitted

ERROR: for php  Cannot start service php: error while creating mount source path '/Users/joe/var/www/vitecraft3/cms/storage/runtime/compiled_templates': mkdir /Users/joe/var/www/vitecraft3/cms/storage/runtime: operation not permitted
ERROR: Encountered errors while bringing up the project.
make: *** [up] Error 1
```

Looks to be an issue with `chown`ing the project dir which fails on volumes listed in the docker-compose.yml with flags appended such as `:delegated` which [no longer appear to be used](https://github.com/docker/for-mac/issues/5402) in latest docker desktop for mac, removing those flags & chowns in the dockerfile do get me a little further though I hit further issues downstream.

Docker v3.4.0
macos vig sur 11.4

**Comment by khalwat** [comment]
This was fixed already; I recently did this from start to finish and recorded a video of doing so here:

https://youtu.be/TkAWDb-NB9E

So I'm sure what is checked into the repo works. If you're still having issues, try creating a new project with a new name (one you haven't used before) to ensure the volumes are re-created.

**Comment by joepagan** [comment]
I tried this 3-4 times yesterday, just tried again this morning with another new dir `vitecraft7`:

```
WARNING: Image for service vite was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating vitecraft7_nginx_1 ...
Creating vitecraft7_redis_1   ... done
Creating vitecraft7_mariadb_1 ... done
Creating vitecraft7_nginx_1   ... done
Creating vitecraft7_php_1     ... error

Creating vitecraft7_vite_1    ... done
ermitted

ERROR: for php  Cannot start service php: error while creating mount source path '/Users/joe/var/www/vitecraft7/cms/storage/runtime/compiled_templates': mkdir /Users/joe/var/www/vitecraft7/cms/storage/runtime: operation not permitted
ERROR: Encountered errors while bringing up the project.
make: *** [up] Error 1

var/www/vitecraft7 on 🐳 v20.10.7 took 1m 24s
```

**Comment by khalwat** [comment]
What host operating system are you using?

**Comment by khalwat** [comment]
Also what version of Docker Desktop are you running?

**Comment by joepagan** [comment]
Docker v3.4.0
macos big sur 11.4

**Comment by khalwat** [comment]
That's the issue -- there's a bug in Docker 3.4.0 for the Mac -- update to 3.5.1. https://github.com/docker/for-mac/issues/5748

**Comment by joepagan** [comment]
Perfect that was it thanks!
