### ISSUE TITLE
Vue replaces all inside "#app" div

### ISSUE THREAD

**Issue by CMeldgaard** [nystudio107/craft#61]
### Question
Hi, im trying to setup a Craft site base on your project template. I have used your vue 2 setup up intil now, where we have a root element with id #app. Inside here the entiry content of the website lives. In this Vue 3 setup, all content inside the #app gets replaces for some reason. I have even tried setting app.ts up with the ["Vue getting started" example](https://v3.vuejs.org/guide/introduction.html#what-is-vue-js). But even here i can't get it to rener the variables or any components thats inserted in the template using twig <component-name></component-name>

Is there something in your setup that makes Vue 3 behave differently ?

**Comment by khalwat** [comment]
Vue 3 by default does _not_ include the template compiler, so it can't compile Vue code on the fly. If you want to do that, you'll need to explicitly include it, for instance:

```js
resolve: {
    alias: {
      '@': './src',
      'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')
    },
  },
```

More info here: https://v3.vuejs.org/guide/installation.html#explanation-of-different-builds

**Comment by Saboteur777** [comment]
I encountered this issue previously, this is how I solved it: 

1. Added `'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')` to `vite.config.js`: 

```
  resolve: {
    alias: {
      '@': './src',
      'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')
    },
  },
```

2. Removed `src/vue/App.vue`, moved its contents to `app.js`, like this:

```
import 'vite/dynamic-import-polyfill';
import '/src/css/app.pcss';
import {createApp} from 'vue';
import CodeHighlight from '/src/vue/CodeHighlight.vue';

// App main
const main = async () => {
  // Create our vue instance
  const app = createApp({
    components: {
      CodeHighlight
    },
    data: () => ({
    }),
    methods: {
    },
    mounted() {
    },
  });

  // Mount the app
  const vm = app.mount('#app');

  return vm;
};

main().then( (vm) => {
  lazyLoading();
});

const lazyLoading = async() => {
  const library = await import ('lazysizes');

  document.addEventListener('lazybeforeunveil', function(e){
    var bg = e.target.getAttribute('data-bg');
    if(bg){
      e.target.style.backgroundImage = 'url(' + bg + ')';
    }
  });
}
```

The `'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')` kicks in when Vite finds the `vue` as a dependency during the compilation (in `.vue` and `.js` files): the path (`path.resolve('./node_modules/vue/dist/vue.esm-bundler.js')`) defined in `vite.config.js` will be used instead of the default. 

3. body.twig: 

```
    <body class="{{ bodyClass }}">
        <section id="app">
            {% block mainMenu %}
                {% include '_components/site/navigation/mainMenu.twig' %}
            {% endblock %}

            <main class="{{ mainClass }} mt-16">
                <section id="content" class="relative">
                    {% block mainContent %}{% endblock %}
                </section>
            </main>

            {% include '_components/site/sections/footer.twig' %}
        </section>
    </body>
```

I think the crucial part here was to remove the intermediary `App.vue` back to `app.js` - after this the behaviour was the same as with the webpack-based buildchain.

**Comment by nicoagp** [comment]
Hi @khalwat, how can I use a single vue 3 component like GalleryBlock.vue in any twig file ? I tried editing the alias but did not work for me, I got the following: Thank you!

`
http://localhost:3000/@id/src/vue/GalleryBlock net::ERR_ABORTED 404 (Not Found)
`

my app.ts


```
// import App from '@/vue/App.vue';
import {createApp} from 'vue';
import GalleryBlock from '@/vue/GalleryBlock';

// Import our CSS
import '@/css/app.css';

// App main
const main = async () => {
  // Create our vue instance
  const app = createApp({
    components: {
      GalleryBlock
    },
  });

  // Mount the app
  return app.mount('#component-container');
};

// Execute async function
main().then(() => {
  console.log('from app.ts');
});

// Accept HMR as per: https://vitejs.dev/guide/api-hmr.html
if (import.meta.hot) {
  import.meta.hot.accept(() => {
    console.log("HMR")
  });
}
```

**Comment by khalwat** [comment]
This isn't related to the boilerplate really, but if you want to do that, you'll need to include the Vue template compiler in your build.

**Comment by nicoagp** [comment]
Thank you @khalwat, yes I asked just in case.
Leaving this comment for anyone want to do the same thing.

Solved it by updating my: 

vite.config.js
```
...
resolve: {
  alias: {
    '@': './src',
    'vue': path.resolve('./node_modules/vue/dist/vue.esm-bundler.js'),
  },
  preserveSymlinks: true,
},
...

```

and 

appj.js (or app.ts)

```
import GalleryBlock from '../vue/GalleryBlock.vue';

// App main
const main = async () => {

  // Async load the Vue 3 APIs we need from the Vue ESM
  const { createApp } = await import(/* webpackChunkName: "vue" */ 'vue');

  // Create our vue instance
  const app = createApp({
    components: {
      GalleryBlock, 
    },
      data() {
          return {
            myProp: null
          }
      },
      mounted() {
        // global mounted
      },
      methods: {
         // global methods
      },
  });

  // Mount the app
  const root = app.mount("#page-container");

  return root;
};

// Execute async function
main().then( (root) => {
  console.log(root)
});

// // Accept HMR as per: https://vitejs.dev/guide/api-hmr.html
if (import.meta.hot) {
  import.meta.hot.accept(() => {
    console.log("HMR")
  });
}

```

**Comment by khalwat** [comment]
Perfect!
