### ISSUE TITLE
Local font files

### ISSUE THREAD

**Issue by CMeldgaard** [nystudio107/craft#63]
### Question
How do you get fonts to get loaded locally when running nodemon ? I'm using a font family that should use a font-file, but i can't see where to add them / what the path should be for it to work locally.

**Comment by iuscare** [comment]
Hey @CMeldgaard you can load them through webpack. See Andrews devmode website for reference:

The font files themselves should be placed in `/src/fonts/`, see:
https://github.com/nystudio107/devmode/tree/master/src/fonts

Load them with webpack `/buildchain/webpack-settings/app.settings:js`:
https://github.com/nystudio107/devmode/blob/ea01ef0b19bbc7badf98054f060a85a5d9c3580e/buildchain/webpack-settings/app.settings.js#L22-L29

Then reference the files in `/cms/templates/_inline_css/site-fonts.css`:
https://github.com/nystudio107/devmode/blob/ea01ef0b19bbc7badf98054f060a85a5d9c3580e/cms/templates/_inline-css/site-fonts.css#L18-L44

**Comment by CMeldgaard** [comment]
@iuscare i've tried that, but since dist doesnt exists locally when running it in nodemon (dev mode), so i still get the same error since it can't load the font files - or am i missing something ?

**Comment by khalwat** [comment]
`dist/` will exist locally if you do a:

```
make build
```

...or there is also no reason you _need_ to run your fonts through webpack. You can always just put the fonts in your `web/` directory manually.
