### ISSUE TITLE
webpack-dev-server static.watch.poll configuration wrong?

### ISSUE THREAD

**Issue by rowild** [nystudio107/craft#66]
### Describe the bug
The configuration of the webpack devServer here:
https://github.com/nystudio107/craft/blob/craft-webpack/buildchain/webpack-configs/dev-server.config.js#L37-L40

uses `watch: { poll: true }`. If I am not mistaken, this is a setting to configure 'chokidar'. According to the webpack 5 documentation it should read `usePolling: [boolean]` instead of `poll`. This is also what the Chokidar documentation says: https://github.com/paulmillr/chokidar#performance

Am I wrong? If so, would you mind to explain, where the setting `poll` is coming from? Thank you!

BTW: Awesome script collection! Thank you!

**Comment by khalwat** [comment]
Yep, looks like it should be changed to `usePolling`

**Comment by khalwat** [comment]
Interestingly, not to be confused with `watchOptions.poll` -> https://webpack.js.org/configuration/watch/#watchoptionspoll

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft/commit/bf760a381640d4e6f673f040d1b4b487f4004acd
