### ISSUE TITLE
Images in src/img not going to dist/img

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft#67]
### Question
I'm relatively new to webpack, and on my first project.
My JS/CSS is compiling absolutely fine, but any PNGs/SVGs in my `src/img` folder is being minified and/or moved into the `dist/img` folder. Tried it using `make dev` `make build` and even `npm run build`.

This might be me not understanding webpack yet, but any suggestions or tips would be appreciated!

**Comment by khalwat** [comment]
Using webpack, if you don't `import` an image into JavaScript, it doesn't know about it. Same goes with fonts or anything else.

So either `import` your resources if you want them as part of the build process, or use a plugin like the webpack copy plugin to copy them into place.

The plugin is baked into my default boilerplate:

https://github.com/nystudio107/craft/blob/craft-webpack/buildchain/webpack-settings/copy.settings.js

Also search this article on "fonts" and "images":

https://nystudio107.com/blog/an-annotated-webpack-4-config-for-frontend-web-development
