### ISSUE TITLE
Installing craft commerce

### ISSUE THREAD

**Issue by Lennso** [nystudio107/craft#68]
### Question
Hi Andrew, i try to install craft commerce and i got some probs with soap and php extensions:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - craftcms/commerce[3.4.0, ..., 3.4.5] require ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - ibericode/vat[1.1.2, ..., 1.2.1] require ext-soap * -> it is missing from your system. Install or enable PHP's soap extension.
    - Root composer.json requires craftcms/commerce ^3.4 -> satisfiable by craftcms/commerce[3.4.0, ..., 3.4.5].

To enable extensions, verify that they are enabled in your .ini files:
    -
    - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-exif.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-shmop.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sysvmsg.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sysvsem.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sysvshm.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/xdebug.ini
    - /usr/local/etc/php/conf.d/zzz-docker-php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

### Additional context
Maybe you can give me a hint?

**Comment by khalwat** [comment]
Yes, you'd need to add the Soap extension. Something like this:

https://github.com/nystudio107/plugindev/blob/develop/docker-config/php-prod-craft/Dockerfile#L42

&

https://github.com/nystudio107/plugindev/blob/develop/docker-config/php-dev-craft/Dockerfile#L42

Then rebuild the images with:

```
docker-compose up --build
```

...from your root project directory.
