### ISSUE TITLE
Missing dots ?

### ISSUE THREAD

**Issue by svale** [nystudio107/craft#7]
Thank you for sharing this (and all the other stuff) - it's much appreciated!

In a test-run of the install I had a hitch with the service-worker install promise failing. Seems to be a couple of missing dots after ".min" (before `{{staticAssetsVersion}}`) in the staticAssets URLs. E.g: https://github.com/nystudio107/craft/blob/27360ee91b80c738c8b5c2d3dbfa77504f1bdf22/templates/sw.js#L32

Perhaps only an issue running on Laravel Valet, but though I let you know anyways.

Cheers!

**Comment by khalwat** [comment]
Thanks for the report -- will fix! :)

**Comment by khalwat** [comment]
This is fixed in 1.0.4:

https://github.com/nystudio107/craft/releases/tag/1.0.4
