### ISSUE TITLE
Installer stops after creating directory

### ISSUE THREAD

**Issue by andersonlyle** [nystudio107/craft#73]
I've been trying to get everything installed, but the installation script dies right after creating the project.  I've tried deleting all the docker volumes, uninstalling and reinstalling docker, but no change.  I'm on an M1 Mac with V 4.3.2 of docker desktop.  

> composer create-project nystudio107/craft:dev-craft-vite testvite --no-install --remove-vcs

Creating a "nystudio107/craft:dev-craft-vite" project at "./testvite"
Installing nystudio107/craft (dev-craft-vite 87fcc798f235eb170b395f6e019fb06cb9e93997)
  - Installing nystudio107/craft (dev-craft-vite 87fcc79): Extracting archive
Created project in /Users/lyle/Sites/testvite
> @php -r "copy('./cms/example.env', './cms/.env');"
> @php -r "copy('./scripts/example.env.sh', './scripts/.env.sh');"
> @php -r "@unlink('composer.json');"
> @php -r "@unlink('composer.lock');"
> @php -r "@unlink('LICENSE.md');"
> @php -r "@unlink('README.md');"

Any help would be appreciated!  Thanks!

**Comment by cavellblood** [comment]
I think you're doing it right. Now you'll need to `cd` into that new directory with `cd testvite`. From there you should be able to get things going by typing `make dev` in that directory. 

The output that you shared above is just showing you that it successfully created that new project from the composer template.

**Comment by andersonlyle** [comment]
You're right, stupid mistake, it's loading fine now!
