### ISSUE TITLE
Permission issue with `make restoredb`, connecting to db via TablePlus

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft#74]
I’m trying to restore the database via `make restoredb mydatabase.sql`, but I get the following error.

```
/bin/sh: ./docker_restore_db.sh: Permission denied
make: *** [restoredb] Error 126
```
Based on the error, it seems that shell script file isn't executable? 

On a related note, I can’t seem to connect to the database via TablePlus. I get `Unknown MySQL server host 'wheat_mariadb_1' (0)` error with the following credentials:
```
Host: myproject_mariadb_1
Port: 3306
User: project
Password: project
Database: project
```

**Comment by khalwat** [comment]
1) Yes, do `chmod a+x docker_restore_db.sh`

2) The host should be `localhost`, because you're attempting to connect to it from outside of the Docker network

**Comment by jayhlee** [comment]
Permissions issue now resolved, but `File not found for variable SRC_DB_PATH` error is now rearing its head.

`localhost` (`127.0.0.1` if you're using TablePlus) works. Thanks, Andrew!

**Comment by khalwat** [comment]
Probably you need to set that in the `.env.sh`?

**Comment by jayhlee** [comment]
I gave that a try, but that didn't seem to work. 

I actually just tried to spin up a fresh install using the latest `craft-vite` branch, but aside from the `make dev` command, the other `make` commands don't seem to work now. For example, if I run `make build`, the process gets stuck at: 
```
Attaching to mysite-mariadb-1, mysite-nginx-1, mysite-php-1, mysite-php_xdebug-1, mysite-queue-1, mysite-redis-1, mysite-vite-1
```
If I run `npm run build` inside the buildchain container (`mysite_vite_1` container), I can get the build to work. But `make composer...`, `make npm...`, etc. all get stuck at the "Attaching to..." process.

**Comment by khalwat** [comment]
This sounds like the Docker container naming issue: https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore/70295720#70295720

**Comment by iuscare** [comment]
@jayhlee did you try `restoredb` with relative or absolute path execution? I can reproduce the error when using relative paths, so maybe try it with an absolute path e.g. (`make restoredb /Users/iuscare/Projects/craft/db-seed/project--2021-05-16-014155--v3.6.14.sql.gz`)

**Comment by jayhlee** [comment]
@iuscare Using an absolute path worked. Thanks!
