### ISSUE TITLE
Docker container names are different to what the makefile expects

### ISSUE THREAD

**Issue by deanfields** [nystudio107/craft#75]
### Describe the bug
I attempted to run the make commands such as ```make composer require xxx```, but it wasn't running, because the if statement:

```

if [ ! "$$(docker ps -q -f name=${CONTAINER})" ]; then \
        docker-compose up; \
fi

```

I looked in the Makefile and the docker dashboard and noticed the following: 

```
CONTAINER?=$(shell basename $(CURDIR))_php_1
BUILDCHAIN?=$(shell basename $(CURDIR))_webpack_1
```

**However the containers are named with hyphens not underscores** - I haven't changed anything with my setup to cause this.

Changing the lines above to use hyphens fixed the problem.

**Comment by khalwat** [comment]
Yeah it's a really annoying problem made worse by the fact that they've changed it back and forth with the Docker Compose API:

https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore/70295720#70295720

The rub is if you have already created your images, it will _keep_ their names even if you do use the v2 API. Read the SE issue in detail.
