### ISSUE TITLE
Set the username and password for the admin account on project creation

### ISSUE THREAD

**Issue by deanfields** [nystudio107/craft#76]
### Is your feature request related to a problem? Please describe.
When setting up the project the username and password for the admin account are set to your details.

### Describe the solution you would like
A simple way to set the username and password when initiating a project 

### Describe alternatives you have considered
Either pass them in when the project is being generated on the command line, or there could be a configuration file that contains some details like the admin username and password that get used when the project is being initialized, it could set other things too

**Comment by khalwat** [comment]
So I'm probably not going to add this, because this is my boilerplate, and so I always want it set up ahead of time for me. But you can do the same thing with a db dump or setup script, sure.
