### ISSUE TITLE
[craft-vite] This localhost page can’t be found

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft#77]
### Question
I'm following directions from this [article](https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms) but am currently stuck at the `yarn run dev` step where if I go to http://localhost:3000 it says `This localhost page can’t be found`. Which seems to me there is some misconfiguration maybe?

Also when editing any of the ./template/**/* files the ViteRestart doesn't get triggered.
And worth noting is when I run `yarn run build` I get the following folder structure:
- web
   - cpresources
   - dist
      - cpresources
      - assets _(name we use instead of `src`, but shouldn't this be `dist`?)_

### Additional context
- We use Valet as the local dev environment instead of Docker. 
- I've done a clean Craft install using composer and installed the craft-vite plugin using the composer command.
- The project is in a folder named `vitecraft` and if I visit `http://vitecraft.test` it does show the Craft welcome page.

**Comment by khalwat** [comment]
Nothing is misconfigured. You should not be going to http://localhost:3000/ -- that is purely the Vite dev server for serving up JavaScript, CSS, and other resources "hot" while in development.

You should be going to http://localhost:8000/ to see the site itself.

**Comment by svondervoort** [comment]
Ah ok, sorry I must have missed that. localhost:8080 does nothing for me (`localhost refused to connect.
`) but when I simply visit `vitecraft.test` it does the live reloading and hot module replacement so I guess we're good to go.

**Comment by khalwat** [comment]
Well, that localhost:8000 URL was assuming you were using the complete Craft boilerplate setup, which runs in Docker. If you're using some other environment, yes, you'd use that URL
