### ISSUE TITLE
Running Craft 4 Beta within Craft Vite Container

### ISSUE THREAD

**Issue by RenegadeMonster** [nystudio107/craft#79]
### Question
I'm playing around with a blank Craft Vite docker image to see if I can get a Craft Beta container up and running to start poking around in and preparing for when Craft 4 is released.

When trying to upgrade Craft 3.7.37 to Craft 4 I get the following error:

```Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
nystudio107/craft-fastcgicachebust 1.0.10 requires craftcms/cms ^3.1.0 -> found craftcms/cms[3.1.0-beta.1, ..., 3.7.37] but it conflicts with your root composer.json require (^4.0.0-beta.1). 
```

However, in the plugin store FastCGI Cache Bust is tagged for Craft 4 comparability. I've tried generating a new lock file and again the same error. 

Just wondering if my best bet to start playing around with Craft 4 would be to nuke that plugin for now and if this is an issue with this container or the plugin.

Thanks,
Chris

**Comment by khalwat** [comment]
So this repo is not intended for Craft 4 (yet) -- but if you want to update it, you can. You just need to change the plugin versions in the `composer.json` to `^4.0.0-beta.1` for any of the nystudio107 plugins

**Comment by RenegadeMonster** [comment]
Thanks @khalwat ,

That did the trick.  Also to note if anyone else is doing this you have to add `"minimum-stability": "dev",` to the composer.json file as well.
