### ISSUE TITLE
Connect to database from Tableplus

### ISSUE THREAD

**Issue by billymedia** [nystudio107/craft#81]
I just installed the starter project, but i cannot see how to connect to the database using a mysql client.
Where would i find the database connection details?

**Comment by khalwat** [comment]
https://nystudio107.com/docs/connect/#configuring-connect

**Comment by billymedia** [comment]
Sorry, not sure how the plugin helps. I want to connect to the database created by the starter project from a mysql client.
Am i missing something? how does the connect plugin help with this?

**Comment by khalwat** [comment]
I'm sorry, I misread the git repository.

If you want to connect to the database, you'd connect to `localhost` port `3306`

The database name is `project` and the password is `project` too.
