### ISSUE TITLE
Access Env variables from vite, app.js, components and/or javascript 

### ISSUE THREAD

**Issue by nicoagp** [nystudio107/craft#86]
### Question
I do have this setup working fine using Docker + Craft + Vite and using javascript and Vue3.

Is there any way I can access variables from the .env file on my src/js/app.js ? 

Thank you

**Comment by khalwat** [comment]
Yes, you can use the node dotenv package, like I did in the old webpack config: https://github.com/nystudio107/craft/blob/craft-webpack/buildchain/webpack-settings/dev-server.settings.js

**Comment by nicoagp** [comment]
Awesome! Thank you Andrew
