### ISSUE TITLE
Setup Config Deploy Production

### ISSUE THREAD

**Issue by nicoagp** [nystudio107/craft#87]
### Question
I am not super savvy in this area ...
When deploying to production, what is the recommended way to go?
Should deploy all containers ?
Just deploy the CMS folder and connect to db ?

### Environment
Using Aws Lightsail but imagine would be similar in other environments/servers

Thank you!

**Comment by khalwat** [comment]
Here's what I currently do: https://nystudio107.com/blog/executing-atomic-deployments
