### ISSUE TITLE
Vite + Vue 3 + Twig

### ISSUE THREAD

**Issue by Toni-hr98** [nystudio107/craft#88]
### Question
I would like to use vite, vue3, and twig together. But how do I load vue components in certain places in my twig files? For example, I want to open a vue modal that uses a `<Slot>` or props in my twig page/file. How do I do that?

Do i have to import/load the components somewhere in the app.js so i can use them in my twig files? 

Are there examples? 

I tried this from older versions that used webpack but its not working.. 

<img width="1165" alt="Schermafbeelding 2023-04-13 om 21 03 28" src="https://user-images.githubusercontent.com/56109782/231858151-29ec8132-7162-4865-ba89-04cbc8c1384c.png">

**Comment by khalwat** [comment]
Maybe this will help: https://www.viget.com/articles/when-and-how-to-use-vue-3-0-with-craft-cms/
