### ISSUE TITLE
Craft requires PHP 7.0 or later

### ISSUE THREAD

**Issue by tinchalamo** [nystudio107/craft#9]
When I run `./craft setup` I get the message "Craft requires PHP 7.0 or later". Is there any way around this requirement on a local install? Usually when I run a Craft 3 install using Composer I can use `--ignore-platform-reqs`.

**Comment by khalwat** [comment]
How are you running Craft 3 if the local PHP isn't 7.0 or later?

**Comment by khalwat** [comment]
So when you do `composer create-project nystudio107/craft craft3 -s RC --ignore-platform-reqs` (or whatever) that's telling Composer to ignore the minimum requirements when _installing_ the package.

That's a separate thing from actually being able to _run_ the installed package (which is what you're doing with `./craft setup`

**Comment by khalwat** [comment]
If you're using MAMP or such you could try `/path/to/mamp/php craft setup` but this is really a Craft CMS 3 support question or a MAMP support question, it doesn't really have anything to do with `nystudio107/craft`
